### ISSUE TITLE
Estimate of computational requirements

### ISSUE THREAD

**Issue by lely475** [facebookresearch/ssl-data-curation#4]
Hi @huyvvo  and team,

Thanks a lot for the great work and code you're providing.
Could you give a rough estimate of the GPU hours required/ computational resources you used for the hierarchical clustering of the web-based images (N=743M) and the amount of time it took? 

Thank you!

**Comment by huyvvo** [comment]
Hello @lely475, 

Thank you for your appreciation of our work. The computation speed depends a lot on the type of devices (GPUs). A rough estimation in our case with A100 gpus is given below:
  - Level 1: 8h of execution time with 16 x 8 gpus
  - Level 2: 15h of execution time with 2 x 8 gpus
  - Level 3: 1.5h of execution time with 1 x 8 gpus
  - Level 4: < 1h of execution time with 1 x 8 gpus
 
Hope that these details help!

**Comment by lely475** [comment]
That helps a lot, thank you!

**Comment by scopello** [comment]
Hi @huyvvo,

Thanks a lot for this great work! I am wondering if there are any parameters users can adjust to reduce the resources needed for level 1? Specifically:

- Does the implementation support sampling of points for computing kmeans clusters? (For example Faiss kmeans has default of 256 sampled points per cluster https://github.com/facebookresearch/faiss/wiki/FAQ#can-i-ignore-warning-clustering-xxx-points-to-yyy-centroids) 
- Are 16 x 8 gpus for level 1  a requirement for memory constraints, or can users use for example 1 x 8  gpus with a longer runtime?

Thank you!

**Comment by huyvvo** [comment]
Hello @scopello,

Unfortunately, the current implementation does not support sampling input points and the 16 x 8 gpus in level 1 is for memory constraints.

However, there are ways we can reduce the computational resources required for level 1. Level 1 is run in two stages for very large data pool. Take our image data pool with 743M images for example. We first run k-means to divide this pool into 100k clusters, then we run k-means separately to divide each cluster into 100 smaller ones. This makes a total of 10M clusters at the end of level 1. The second stage does not actually require 16x8 gpus, you can run it with 8 gpus for longer. For the first stage, similar to faiss, you can resample 100k * 256 points instead of using all 743M points to reduce the resource requirement. After obtaining 100k centroids on 100k * 256 points, we can then assign the 743M points into these centroids to form the clusters of stage 1 in level 1. You can of course perform this assignment step with 8 gpus for longer. After obtaining the 10M clusters of level 1 with this work around, you can launch the other levels as usual.
