### ISSUE TITLE
Input Data Clarification

### ISSUE THREAD

**Issue by gabricampanella** [facebookresearch/ssl-data-curation#6]
Dear @huyvvo and team, thank you for the great work you are doing.

I have read the paper with great interest and I am looking to apply your method to a large dataset of medical images. After an initial pass through the code provided, I have made the following observations:
- The input embeddings are stored as a single array. So, for your 743M images experiment with a ViT large embedding (1024 features), you have a single file massive file saved. To my calculations, that would be over 5TB. Is this correct?
- The input embeddings file above is memory mapped and only relevant sections are loaded in each process.
- Each process receives a slice of the full data. So in your 743M experiment you used 16 * 8 GPUS (as seen in the config file provided) = 128GPUs = 128 processes. The totality of the data is processed in parallel across the 128 processes.
- 5TB / 128 processes is around 39GB per process.
Am I correct so far? 

Any clarification would be greatly appreciated.

**Comment by huyvvo** [comment]
Hello @gabricampanella, 

Thank you for your appreciation of our work!

As for your questions, your observations are mostly correct, except that we save our embeddings in float16 their total size is about 1.38TB (743e6*1024/) instead of 5TB. During the execution of hierarchical k-means, we cast the embeddings to float64 (important!, otherwise, the computation is not correct), so each process manages about 44GB.

Hope that these details help!

**Comment by gabricampanella** [comment]
Understood. Thank you!
